### ISSUE TITLE
Lier pratiques et accessibilités

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#331] opened 2015-08-20 08:06 UTC
Lorsque le champ USAGE (itinéraires) a été remplacé par PRATIQUES et ACCESSIBILITÉS (v0.30.0), il était précisé que les valeurs de ces champs devaient être liées. En effet, pour la pratique PÉDESTRE, on ne doit proposer que les ACCESSIBILITÉS correspondantes (joelette, fauteuil roulant, poussette par exemple). Caleche, atellage.... pour EQUESTRE. Cela ne semble pas être le cas dans la BDD ni Geotrek-admin mais pas non plus dans Geotrek-rando apparemment. Vu sur http://rando.loire-atlantique.fr/ où les accessibilités VTT et ÉQUESTRE sont proposés dans les filtres de la catégorie RANDO PÉDESTRE.

Il me semble que le plus opérationnel pour gérer cela aurait été de lier les champs et les valeurs dans la BDD ?

Voir https://github.com/makinacorpus/Geotrek/issues/1375

**Comment by SBats** [comment] 2015-12-03 16:46
When we explode trekking by the different uses (on foot, horse, cycle, ...) the problem is not present as only the accessibility concerned are displayed in the corresponding filters.

On the other case, this demande is kind of complexe as it may imply that when you chose a use, the accessibilities are filtered depending on this one, but why not filtering uses when an accessibility is checked ? This need to be really thinked and probably will need someone to invest on it.

**Comment by camillemonchicourt** [comment] 2015-12-04 12:45
OK it's all good if only the values concerned are displayed in each filter. 
I noticed it as accessibilities filters values are very strange on CG44 Geotrek-rando. But maybe it is due to their datas or to an older version. 

Indeed no need to do something complicated in the case of a Geotrek-rando where practices are not exploded in categories. 
No need to have filter depending on another filter...
In this case practice and accessibility filters should display all values everytime and it's all good. 

The only important point is that when practices are exploded into categories, we dont display "poussette" accessibility when we are in VTT category. And from what I understand it will not be the case if none of VTT treks have "poussette" accessibility, which shouldnt happen.... :-)

Thanks.

**Comment by SBats** [comment] 2015-12-04 13:28
Yes that's it.

For CG44, some of their treks are accesible via foot, VTT, and horse but are mostly made for one or another use. That's why you have pedestrian filter on horse and vtt categories filters, etc ...

So I think we can close this issue for now as we agree on this. If we come to the feeling that we need more complex interactions between filters, we'll reopen detailed issues at that moment.

**Closed by SBats** 2015-12-04 13:28 UTC
Labels: enhancement

**Comment by camillemonchicourt** [comment] 2015-12-04 13:38
OK
